---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
Sys.setenv(RETICULATE_PYTHON = '/Users/bade228/opt/anaconda3/envs/r2/bin/python3')
library(reticulate)
library(readxl)
library(stringr)
library(dplyr)
library(tidyr)
library(nationalparkcolors)
library(pheatmap)
library(cowplot)
library(ggplot2)
syn=reticulate::import('synapseclient')
sync=syn$login()
pal = nationalparkcolors::park_palette('Acadia')
```
```{r}
##get annotations
queryRes <- sync$tableQuery('SELECT zScore,totalCounts,specimenID,Symbol,individualID,experimentalCondition FROM syn22878645')
queryTable <- rbind(queryRes$asDataFrame())
#tabres2 = synTableQuery('SELECT zScore,totalCounts,specimenID,Symbol,individualID,experimentalCondition FROM syn21222341')
```

```{r}
prepCorrelationData<- function(queryTable) {
  rnaseq<- queryTable %>%
           distinct()%>%
           #mutate(specimenID=str_replace_all(specimenID,fixed('NF0007-2-M+C'),'NF0007-2- M+C'))%>%
           #mutate(specimenID=str_replace_all(specimenID,fixed('NF0007-2-M+C+F'),'NF0007-2- M+C+F'))%>%
           mutate(specimenID=str_replace_all(specimenID,"S $","S")) %>%
           mutate(specimenID=str_replace_all(specimenID,fixed("- "),"")) %>%
           mutate(specimenID=str_replace_all(specimenID,fixed(" "),"-"))
  print(head(rnaseq))
  # remove known bad data
  badSpecs=c("NF0009-1-M","NF0009-1-M+C","NF0002-8-19-M+C+F","NF0002-8-19-D+C","NF0002-8-19-D+C+F","NF0002-8-19-S+C")
  rnaseq<-rnaseq%>%
          subset(!specimenID%in%badSpecs)
  print(rnaseq$specimenID)
  print('dividing pt')
  annotes<-dplyr::select(rnaseq, specimenID, individualID, experimentalCondition)
           #%>%
           #separate(specimenID,into=c('altID','extra'),sep=' ',remove=F)%>%
           #mutate(altID=stringr::str_replace(altID,'-$',''))%>%
           #dplyr::select(-extra)%>%
           #distinct()
  annotes$altID <- annotes$specimenID
  annotes <- annotes %>% 
             distinct() %>%
             tibble::remove_rownames() %>%
             tibble::column_to_rownames('specimenID')
  print(head(annotes))
  #rownames(annotes)<-annotes$specimenID
  #annotes<-annotes%>%
           
  annotes$Media<-rep("None",nrow(annotes))
  annotes$Media[grep("DMEM",annotes$experimentalCondition)]<-'DMEM'
  annotes$Media[grep("StemPro",annotes$experimentalCondition)]<-'StemPro'
  annotes$Media[grep('Mammo',annotes$experimentalCondition)]<-'Mammo'
  print(head(annotes))

  pats=annotes$altID[grep('patient',annotes$individualID)]
  print(head(pats))
  specs<-c(rownames(annotes)[grep('patient',rownames(annotes))],
         'NF0002-8-19 M','NF0009-1- M+C+F','NF0012-3-6 M')
  print(head(specs))
  for(x in c('kines','Forskoline')){
    annotes[[x]]<-FALSE
    annotes[[x]][grep(x,annotes$experimentalCondition)]<-TRUE
    # annotes[[x]]=as.character(annotes)
  }
  annotes<-annotes%>%
           dplyr::rename(Cytokines='kines')#%>%dplyr::select(-experimentalCondition)
  print(annotes)
  nannotes<-apply(annotes,2,as.character)
  rownames(nannotes)<-rownames(annotes)
  print(head(nannotes))
  orgs<-subset(annotes,experimentalCondition!='NaN')$altID
  print(head(orgs))
  biga<-annotes%>% 
        subset(altID%in%orgs)%>%
        tibble::rownames_to_column('specimenID')%>%
        dplyr::select(-c(individualID,experimentalCondition))%>%
        mutate(val=1) %>% 
        pivot_wider(names_from = Media,values_from = val) %>% 
        mutate(across(-c(Cytokines,Forskoline,altID,specimenID), ~replace_na(.x, 0))) %>%
        mutate(across(-c(Cytokines,Forskoline,altID,specimenID), ~ifelse(.x==1, TRUE,FALSE)))
  print(head(biga))
  mat<-rnaseq%>%
       dplyr::select(specimenID,zScore,Symbol)%>%
       tidyr::pivot_wider(values_from=zScore,names_from=specimenID,
                          values_fn=list(zScore=mean),values_fill=list(zScore=0))%>%
       tibble::column_to_rownames('Symbol')%>%
       as.matrix()
  print(head(mat))
  vars<-apply(mat,1,var,na.rm=T)%>%
        sort(decreasing=T)
  print(head(vars))
  return(list(mat=mat,annotes=annotes,pat=pats,vars=vars))
}
```

```{r}
prep.res <- prepCorrelationData(queryTable)
```

```{r}
plotCorrelationBetweenSamps<-function(prep.res,prefix='geneExpression'){
  mat = prep.res$mat
  annotes = prep.res$annotes
  pat = prep.res$pat
  orgs<-setdiff(annotes$altID,pat)
  #now compute the correlation values
  dlist<-lapply(orgs,function(pat){
    iannote<-annotes%>%
             dplyr::select(experimentalCondition,Media,Cytokines,Forskolin='Forskoline')
    norm=iannote%>%
         subset(experimentalCondition=='None')%>%
         rownames()
    norcors<-sapply(setdiff(rownames(iannote),norm),function(x) 
             cor(mat[,norm],mat[,x],method='spearman'))
    pdat<-iannote%>%
          subset(experimentalCondition!="None")%>%
          dplyr::select(Media,Cytokines,Forskolin)%>%
          cbind(Similarity=norcors)
    return(pdat)
  })

  names(dlist)<-orgs
  ddf<-do.call(rbind,lapply(names(dlist),function(x) data.frame(Patient=x,dlist[[x]])))%>%
       tibble::rownames_to_column('altID')
  #write.csv(ddf,paste0(prefix,'orgCorrelations.csv'),row.names=F)
  names(dlist)<-orgs
  plist<-lapply(orgs,function(pat){
    pdat<-dlist[[pat]]
    pdat%>%ggplot(aes(y=Similarity,x=Media,shape=Forskolin,color=Cytokines))+
    geom_point(aes(size=10))+scale_colour_manual(values=pal)+
    ggtitle(pat)
  })  

  res=cowplot::plot_grid(plotlist=plist)
  ggsave(filename=paste0('test','corPlots.pdf'),res,width=10) #prefix
  return(ddf)
}
```

```{r}
plotCorrelationBetweenSamps(prep.res)
```
```{r}
queryTable
```

```{r}

```

```{r}

```



```{r}

```

